services:
  - type: web
    name: discord-music-bot
    env: node
    plan: free
    buildCommand: apt-get update && apt-get install -y ffmpeg && npm install
    startCommand: node bot.js
    envVars:
      - key: NODE_ENV
        value: production
